/**
 * prologue.js — Dialogue for the Prologue sequence
 * Source: FULL_SCENE_SPEC.md
 *
 * Scene 1: Computer Laboratory (Late Afternoon)
 * Scene 2: Awakening (12:04 AM)
 * Scene 3: Crossroads (12:06 AM)
 *
 * Format: { id, speaker, text, portrait, background, sfx }
 *   speaker:    null = narration (rendered in italic, no nameplate)
 *   portrait:   null = no character portrait shown
 *   background: null = keep current background; string = switch to this texture key
 *   sfx:        null = no sound; string = placeholder sound key
 */

export const prologue = [
  // ── Scene 1: Computer Laboratory (Late Afternoon) ──────────────────────────
  {
    id: 'p_1_01',
    bgm: 'bgm_afternoon',
    speaker: null,
    text: 'Computer Laboratory, daylight. Students at desks, professor addressing class, protagonist visible at back looking exhausted.',
    portrait: null,
    background: 'bg_comlab',
    sprite: null,
    sfx: null,
  },
  {
    id: 'p_1_02',
    speaker: 'Professor',
    text: 'Your capstone proposal is due next week.',
    portrait: null,
    background: null,
    sprite: null,
    sfx: null,
  },
  {
    id: 'p_1_03',
    speaker: 'Professor',
    text: 'Make sure your documentation is complete.',
    portrait: null,
    background: null,
    sprite: null,
    sfx: null,
  },
  {
    id: 'p_1_04',
    speaker: null,
    text: 'Students begin packing up',
    portrait: null,
    background: null,
    sprite: null,
    sfx: 'sfx_hallway',
  },
  {
    id: 'p_1_05',
    speaker: null,
    text: 'Protagonist looks tired',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_default',
    sfx: null,
  },
  {
    id: 'p_1_06',
    speaker: 'Protagonist (Thought)',
    text: 'Just five more minutes...',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_monitor',
    sfx: null,
  },
  {
    id: 'p_1_07',
    speaker: 'Protagonist (Thought)',
    text: "I'll finish it...",
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_monitor',
    sfx: null,
  },
  {
    id: 'p_1_08',
    speaker: 'Protagonist (Thought)',
    text: 'If I stop now...',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_monitor',
    sfx: null,
  },
  {
    id: 'p_1_09',
    speaker: 'Protagonist (Thought)',
    text: "I'll just have even more work tomorrow.",
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_monitor',
    sfx: null,
  },
  {
    id: 'p_1_10',
    speaker: null,
    text: 'Eyes closing/head lowering',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_eyes_closed',
    sfx: null,
  },
  {
    id: 'p_1_11',
    speaker: null,
    text: 'Head resting on desk',
    portrait: null,
    background: 'bg_comlab',
    sprite: null,
    sfx: null,
  },

  // Fade to black transition
  {
    id: 'p_1_12',
    speaker: null,
    text: 'Transitioning...',
    portrait: null,
    background: null,
    sprite: null,
    sfx: null,
  },

  // ── Scene 2: Awakening (1:20 AM) ──────────────────────────────────────────
  // from black then transition
  {
    id: 'p_2_01',
    bgm: 'bgm_main',
    speaker: null,
    text: 'A Mysterious Situation.',
    portrait: null,
    background: null,
    sprite: null,
    sfx: null,
  },
  {
    id: 'p_2_02',
    speaker: null,
    text: 'Computer Laboratory, dark/empty.',
    portrait: null,
    background: 'bg_monitor',
    sprite: null,
    sfx: null,
    mood: 'night',
  },
  {
    id: 'p_2_03',
    speaker: null,
    text: 'Lifts her head, feeling groggy.',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_monitor',
    sfx: null,
    mood: 'night',
  },
  {
    id: 'p_2_04',
    speaker: 'Protagonist',
    text: '...?',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_shocked',
    sfx: null,
    mood: 'night',
  },
  {
    id: 'p_2_05',
    speaker: 'Protagonist',
    text: 'Hm...?',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_shocked',
    sfx: null,
    mood: 'night',
  },
  {
    id: 'p_2_06',
    speaker: null,
    text: 'Empty dark classroom, no students/professor.',
    portrait: null,
    background: 'bg_comlab',
    sprite: null,
    sfx: null,
    mood: 'night',
  },
  {
    id: 'p_2_07',
    speaker: 'Protagonist',
    text: 'Everyone...',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_default',
    sfx: null,
    mood: 'night',
  },
  {
    id: 'p_2_08',
    speaker: 'Protagonist',
    text: '...already left?',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_shocked',
    sfx: null,
    mood: 'night',
  },
  {
    id: 'p_2_09',
    speaker: null,
    text: 'Phone close-up — screen lighting up.',
    portrait: null,
    background: 'bg_comlab',
    overlay: 'bg_ground',
    cg: 'bg_PHONE',
    sprite: null,
    mood: 'night',
    sfx: null,
  },

  // ── Scene 3: Crossroads (1:20 AM) ─────────────────────────────────────────
  {
    id: 'p_3_01',
    speaker: null,
    text: 'Empty campus grounds, buildings, trees swaying, no lights.',
    portrait: null,
    background: 'bg_outside',
    sprite: null,
    sfx: null,
  },
  {
    id: 'p_3_02',
    speaker: 'Protagonist',
    text: '...',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_default',
    sfx: null,
  },
  {
    id: 'p_3_03',
    speaker: 'Protagonist',
    text: 'This...',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_default',
    sfx: null,
  },
  {
    id: 'p_3_04',
    speaker: 'Protagonist',
    text: "...doesn't make any sense.",
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_default',
    sfx: null,
  },
  {
    id: 'p_3_05',
    speaker: null,
    text: 'She walks around.',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_default',
    sfx: 'sfx_gravel',
  },
  {
    id: 'p_3_06',
    speaker: 'Protagonist',
    text: 'Hello...?',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_default',
    sfx: null,
  },
  {
    id: 'p_3_07',
    speaker: 'Protagonist',
    text: 'Is anyone still here?',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_default',
    sfx: null,
  },
  {
    id: 'p_3_08',
    speaker: null,
    text: 'Quiet and Windy...',
    portrait: null,
    background: null,
    sprite: null,
    sfx: null,
  },
  {
    id: 'p_3_09',
    speaker: null,
    text: 'Phone close-up — reads "1:20 AM," "No Signal," "No Notifications"',
    portrait: null,
    background: 'bg_outside',
    overlay: 'bg_ground',
    cg: 'bg_PHONE',
    sprite: null,
    sfx: null,
  },
  {
    id: 'p_3_10',
    speaker: 'Protagonist',
    text: 'Oh great...',
    portrait: 'port_mc_default',
    background: 'bg_outside',
    sprite: 'spr_mc_default',
    sfx: null,
  },
  {
    id: 'p_3_11',
    speaker: 'Protagonist',
    text: 'Seriously...?',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_shocked',
    sfx: null,
  },
  {
    id: 'p_3_12',
    speaker: null,
    text: 'Nervously laughing...',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_default',
    sfx: null,
  },
  {
    id: 'p_3_13',
    speaker: null,
    text: 'She walks back toward the dark computer lab.',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_default',
    sfx: 'sfx_gravel',
  },
  {
    id: 'p_3_14',
    speaker: null,
    text: 'Arrives at the door...',
    portrait: null,
    background: 'bg_door',
    sprite: null,
    sfx: null,
  },
  {
    id: 'p_3_15',
    speaker: null,
    text: 'Door does not open...',
    portrait: null,
    background: null,
    sprite: null,
    sfx: null,
  },
  {
    id: 'p_3_16',
    speaker: 'Protagonist',
    text: 'Huh...?',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_shocked',
    sfx: null,
  },
  {
    id: 'p_3_17',
    speaker: null,
    text: 'Trying handle again, harder...',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_shocked',
    sfx: 'sfx_heavy',
  },
  {
    id: 'p_3_18',
    speaker: null,
    text: 'Still locked...',
    portrait: null,
    background: null,
    sprite: null,
    sfx: null,
  },
  {
    id: 'p_3_19',
    speaker: 'Protagonist',
    text: 'What...? No, no...',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_shocked',
    sfx: null,
  },
  {
    id: 'p_3_20',
    speaker: 'Protagonist',
    text: 'It was open just a second ago...',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_shocked',
    sfx: null,
  },
  {
    id: 'p_3_21',
    speaker: null,
    text: 'Protagonist knocking on door.',
    portrait: 'port_mc_default',
    background: 'bg_door',
    sprite: 'spr_mc_shocked',
    sfx: 'sfx_heavy',
  },
  {
    id: 'p_3_22',
    speaker: 'Protagonist',
    text: 'Hello?!',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_shocked',
    sfx: null,
  },
  {
    id: 'p_3_23',
    speaker: 'Protagonist',
    text: 'Is anyone inside?!',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_shocked',
    sfx: null,
  },
  {
    id: 'p_3_24',
    speaker: null,
    text: 'No answer, only wind...',
    portrait: null,
    background: null,
    sprite: null,
    sfx: null,
  },
  {
    id: 'p_3_25',
    speaker: null,
    text: 'Turns around slowly, breathing heavier...',
    portrait: 'port_mc_default',
    background: null,
    sprite: 'spr_mc_shocked',
    sfx: null,
  },
  {
    id: 'p_3_26',
    speaker: null,
    text: 'Campus map appears — three route choices in dialogue box:\n> Quadrangle\n> New Building\n> Court',
    portrait: null,
    background: 'bg_outside',
    overlay: 'bg_ground',
    cg: 'bg_MAP',
    sprite: null,
    sfx: null,
  },
  {
    id: 'p_3_27',
    speaker: null,
    text: 'Meanwhile... a shadowy entity watches her from behind.',
    portrait: null,
    background: null,
    sprite: null,
    sfx: null,
  },
  {
    id: 'p_3_28',
    speaker: null,
    text: 'Entering the map',
    portrait: null,
    background: null,
    sprite: null,
    sfx: null,
  },
];
